name: videoinr
channels:
  - pytorch
  - nvidia # for cuda
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip # for pip dependencies
  - ninja # fast build times (for DCNv2 install)
  - pytorch::pytorch=2.0.1 # machine learning
  - pytorch::torchvision=0.15.2
  - pytorch-cuda=11.8 # affects pytorch version, 11.8 for latest
  # - cudatoolkit=11.8 # UNCOMMENT if having issues with CUDA
  # - cuda-nvcc=11.8 # UNCOMMENT FOR Windows ONLY; compiler
  - gxx=11.8 # UNCOMMENT FOR Linux ONLY; compiler
  - pyyaml # read yaml config files
  - tqdm # loop progress bars
  - pillow # image processing
  - python-lmdb # database management
  - ffmpeg # for video conversion & processing
  - ipython # optional
  - ipykernel # optional
  - pip:
      - opencv-python # computer vision ai tools
      # - miss_hit # optional, matlab formatter
      - ./models/modules/DCNv2 # auto-install local DCNv2 module

# NOTE
# - Must have CUDA-compatible GPUs with latest drivers installed.
# - NO NEED to install CUDA toolkit on system, this environment is sufficient.
# - Windows: MUST install MSVC on system (VS 2017-2022 for CUDA 11.8).
#   Should also install nvcc eg via 'cuda-nvcc' above.
# - Linux: MUST install gcc & g++ eg via 'gxx' dependency above.
