name: videoinr
channels:
  - pytorch
  - nvidia/label/cuda-11.8.0 # MUST be 11.8
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip # for pip dependencies
  - ninja # fast build times (for dcnv2 install)
  - pytorch::pytorch=2.0.1 # machine learning
  - pytorch::torchvision=0.15.2 # vision tools
  - pytorch-cuda=11.8 # MUST be 11.8
  - cuda=11.8 # cuda toolkit & compilers
  - gxx>=11.8 # UNCOMMENT for Linux: compiler
  - pyyaml # read yaml config files
  - tqdm # loop progress bars
  - pillow # image processing
  - python-lmdb # database management
  # - ffmpeg # OPTIONAL: video conversion & processing
  # - ipython # OPTIONAL: test/debugging
  # - ipykernel # OPTIONAL: test/debugging
  - pip:
      - opencv-python # computer vision ai tools
      # - miss_hit # OPTIONAL: matlab formatter
      - ./models/modules/DCNv2 # auto-install local DCNv2 module

# NOTE
# - Must have CUDA-compatible GPUs with latest drivers installed.
# - NO NEED to install CUDA toolkit on system, this environment is sufficient.
# - Windows: MUST install MSVC on system (VS 2017-2022 for CUDA 11.8).
# - Linux: MUST install gcc & g++ eg via 'gxx' dependency above.
